##################################################################
#
# production.yml
#
# author: Rion Dooley <dooley@tacc.utexas.edu>
#
# This is a docker compose file for running the Lightning data
# vizualization server in moderate production outside of Heroku
# using a PostgreSQL database, reverse proxy, and horizontal scaling.
# The server will be available on ports 80 and 443 on your Docker
# host.
#
# To add authentication to the server, or leverage Amazon S3 storage,
# fill in the environment variables with the appropriate values.
#
# Run with:
#
# docker-compose -f production.yml
#
# Notes:
#
# - Log management, database persistence, and monitoring are
#   intentionally left out of this orchestration so you can use
#   your favorite solutions.
#
# - To add ssl to the above proxy, replace the %%SSL_CERTIFICATE_PATH%%
#   value with the path to the directory containing your SSL certs
#   and set SSL: TRUE in the proxy environment section
#   ssl cert folder SSL add a proxy server such as.
#
# - To scale the lightning server, use fig to start up more web
#   containers. The following command should be sufficient.
#
#   docker-compose -f production.yml scale web=2
#
###################################################################
proxy:
  image: jwilder/nginx-proxy
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  ports:
    - "80:80"
    - "443:443"
  environment:
    SSL: FALSE
web:
  extends: 
    file: common.yml
    service: web
  command: bash -c "node server.js"
  links:
    - db
  environment:
    VIRTUAL_PORT: 3000
    VIRTUAL_HOST: docker.example.com
    NODE_ENV: production
    DATABASE_URL: lightning:changeit@db:5432/postgres
    LIGHTNING_USERNAME:
    LIGHTNING_PASSWORD:
    S3_KEY:
    S3_BUCKET:
    S3_SECRET:
db:
  image: postgres
  environment:
    POSTGRES_USER: lightning
    POSTGRES_PASSWORD: changeit
  ports:
    - 5432